/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}", "../ui/src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#adc7f7",
        "on-primary-fixed-variant": "#2d476f",
        "tertiary-fixed": "#d9e3f9",
        "surface": "#f7fafc",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffddba",
        "surface-container-high": "#e5e9eb",
        "on-primary-container": "#86a0cd",
        "secondary": "#875200",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#ffb866",
        "surface-bright": "#f7fafc",
        "on-primary": "#ffffff",
        "primary-container": "#1a365d",
        "on-secondary-fixed-variant": "#673d00",
        "surface-container-low": "#f1f4f6",
        "primary-fixed": "#d6e3ff",
        "tertiary-container": "#2c3647",
        "on-primary-fixed": "#001b3c",
        "inverse-on-surface": "#eef1f3",
        "secondary-container": "#ffb55c",
        "surface-tint": "#455f88",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#959fb3",
        "on-surface-variant": "#43474e",
        "on-secondary-fixed": "#2b1700",
        "on-tertiary-fixed-variant": "#3d4759",
        "on-background": "#181c1e",
        "outline": "#74777f",
        "background": "#f7fafc",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "on-error-container": "#93000a",
        "primary": "#002045",
        "tertiary-fixed-dim": "#bdc7dc",
        "on-secondary-container": "#744600",
        "on-tertiary-fixed": "#121c2c",
        "inverse-surface": "#2d3133",
        "on-surface": "#181c1e",
        "tertiary": "#172131",
        "surface-container": "#ebeef0",
        "on-secondary": "#ffffff",
        "inverse-primary": "#adc7f7",
        "on-error": "#ffffff",
        "outline-variant": "#c4c6cf",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d7dadc",
        "success": "#166534",
        "success-container": "#dcfce7",
        "on-success-container": "#14532d",
        "warning": "#d97706",
        "warning-container": "#fef3c7",
        "on-warning-container": "#78350f",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        unit: "4px",
        xs: "4px",
        md: "16px",
        xl: "40px",
        sm: "8px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "headline-lg-mobile": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "display-lg": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
